-- NodeGuard production hardening and paper-aligned operational features.

alter table public.profiles
add column if not exists is_active boolean not null default true;

alter table public.incidents
add column if not exists validation_status text not null default 'pending_review'
  check (validation_status in ('pending_review', 'confirmed', 'false_alarm')),
add column if not exists validated_by uuid references public.profiles(id) on delete set null,
add column if not exists validated_at timestamptz;

update public.incidents
set validation_status = case
  when status = 'false_alert' then 'false_alarm'
  when status = 'new_alert' then 'pending_review'
  else 'confirmed'
end
where validation_status = 'pending_review';

-- Keep the original demonstration records internally consistent so response-time
-- analytics are not distorted when this migration is applied after the seed.
update public.incident_status_updates isu
set created_at = i.occurred_at
from public.incidents i
where isu.incident_id = i.id
  and isu.remarks = 'Initial seeded status.';

create table if not exists public.response_resources (
  id uuid primary key default gen_random_uuid(),
  public_code text not null unique,
  resource_type text not null check (resource_type in (
    'Ambulance', 'Fire Truck', 'Rescue Vehicle', 'Patrol Vehicle',
    'Communication Radio', 'First Aid Kit', 'Rescue Equipment',
    'Water Rescue Equipment'
  )),
  unit_name text not null,
  agency text not null check (agency in ('MDRRMO', 'PNP', 'BFP', 'EMS', 'Barangay Responders')),
  status text not null default 'available' check (status in (
    'available', 'dispatched', 'under_maintenance', 'unavailable', 'reserved'
  )),
  base_location text not null,
  assigned_incident_public_id text references public.incidents(public_id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resource_assignments (
  id uuid primary key default gen_random_uuid(),
  resource_id uuid not null references public.response_resources(id) on delete cascade,
  incident_id uuid not null references public.incidents(id) on delete cascade,
  assigned_by uuid references public.profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  released_at timestamptz,
  notes text
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists resources_status_idx
on public.response_resources(status);
create index if not exists resource_assignments_incident_idx
on public.resource_assignments(incident_id, assigned_at desc);
create index if not exists audit_logs_entity_idx
on public.audit_logs(entity_type, entity_id, created_at desc);

drop trigger if exists response_resources_set_updated_at on public.response_resources;
create trigger response_resources_set_updated_at
before update on public.response_resources
for each row execute function public.set_updated_at();

alter table public.response_resources enable row level security;
alter table public.resource_assignments enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.is_nodeguard_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_active
      and role in ('admin', 'super_admin')
  );
$$;

grant execute on function public.is_nodeguard_admin() to authenticated;

create or replace function public.is_active_nodeguard_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and is_active
  );
$$;

grant execute on function public.is_active_nodeguard_user() to authenticated;

create or replace function public.can_read_nodeguard_incident(p_incident_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.is_active
      and (
        p.role in ('admin', 'super_admin')
        or not exists (
          select 1 from public.responders own where own.profile_id = p.id
        )
        or exists (
          select 1
          from public.responders r
          join public.incidents i on i.assigned_responder_name = r.name
          where r.profile_id = p.id and i.id = p_incident_id
        )
      )
  );
$$;

grant execute on function public.can_read_nodeguard_incident(uuid) to authenticated;

drop policy if exists "authenticated profiles can read profiles" on public.profiles;
create policy "users read own profile and admins read profiles" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_nodeguard_admin());

create or replace function public.protect_nodeguard_identity_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' then
    if tg_table_name = 'profiles'
      and (new.role is distinct from old.role or new.is_active is distinct from old.is_active)
    then
      raise exception 'Role and active-state changes require an administrator.';
    end if;
    if tg_table_name = 'responders'
      and not public.is_nodeguard_admin()
      and (
        new.id is distinct from old.id
        or new.profile_id is distinct from old.profile_id
        or new.public_code is distinct from old.public_code
        or new.name is distinct from old.name
        or new.role is distinct from old.role
        or new.agency_unit is distinct from old.agency_unit
        or new.contact_number is distinct from old.contact_number
        or new.current_assignment is distinct from old.current_assignment
      )
    then
      raise exception 'Responder identity and assignment changes require an administrator.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_identity_columns on public.profiles;
create trigger profiles_protect_identity_columns
before update on public.profiles
for each row execute function public.protect_nodeguard_identity_columns();

drop trigger if exists responders_protect_identity_columns on public.responders;
create trigger responders_protect_identity_columns
before update on public.responders
for each row execute function public.protect_nodeguard_identity_columns();

drop policy if exists "authenticated users can read incidents" on public.incidents;
create policy "operators read authorized incidents" on public.incidents
for select to authenticated
using (public.can_read_nodeguard_incident(id));

drop policy if exists "authenticated users can read operational responders" on public.responders;
create policy "active users read operational responders" on public.responders
for select to authenticated
using (public.is_active_nodeguard_user());

drop policy if exists "authenticated users can read device locations" on public.device_locations;
create policy "active users read device locations" on public.device_locations
for select to authenticated
using (public.is_active_nodeguard_user());

drop policy if exists "authenticated users can read assignments" on public.incident_assignments;
create policy "users read assignments for visible incidents" on public.incident_assignments
for select to authenticated
using (public.can_read_nodeguard_incident(incident_id));

drop policy if exists "authenticated users can read status updates" on public.incident_status_updates;
create policy "users read updates for visible incidents" on public.incident_status_updates
for select to authenticated
using (public.can_read_nodeguard_incident(incident_id));

drop policy if exists "authenticated users can update device buzzer state" on public.device_locations;
create policy "admins update registered devices" on public.device_locations
for update to authenticated
using (public.is_nodeguard_admin())
with check (public.is_nodeguard_admin());

drop policy if exists "authenticated users can insert buzzer commands" on public.device_buzzer_commands;
create policy "users insert attributed buzzer commands" on public.device_buzzer_commands
for insert to authenticated
with check (requested_by = auth.uid());

drop policy if exists "authenticated users can read buzzer commands" on public.device_buzzer_commands;
create policy "users read own buzzer commands and admins read all" on public.device_buzzer_commands
for select to authenticated
using (public.is_nodeguard_admin() or requested_by = auth.uid());

drop policy if exists "authenticated responders can submit status updates" on public.incident_status_updates;
create policy "assigned responders and operators submit status updates"
on public.incident_status_updates
for insert to authenticated
with check (
  created_by = auth.uid()
  and public.is_active_nodeguard_user()
  and incident_status_updates.status in (
    'assigned', 'en_route', 'on_scene', 'responding', 'resolved', 'need_backup'
  )
  and (
    public.is_nodeguard_admin()
    or exists (
      select 1
      from public.responders r
      join public.incidents i on i.id = incident_status_updates.incident_id
      where r.profile_id = auth.uid()
        and r.name = i.assigned_responder_name
    )
    or not exists (
      select 1 from public.responders r where r.profile_id = auth.uid()
    )
  )
);

drop policy if exists "users can read own notifications" on public.notifications;
create policy "users read own notifications and admins read all" on public.notifications
for select to authenticated
using (recipient_profile_id = auth.uid() or public.is_nodeguard_admin());

drop policy if exists "authenticated users can read voice context metadata" on public.voice_contexts;
create policy "users read voice metadata for visible incidents" on public.voice_contexts
for select to authenticated
using (public.can_read_nodeguard_incident(incident_id));

drop policy if exists "authenticated users can read resources" on public.response_resources;
create policy "authenticated users can read resources" on public.response_resources
for select to authenticated using (public.is_active_nodeguard_user());

drop policy if exists "authenticated users can read resource assignments" on public.resource_assignments;
create policy "authenticated users can read resource assignments" on public.resource_assignments
for select to authenticated using (true);

drop policy if exists "admins can read audit logs" on public.audit_logs;
create policy "admins can read audit logs" on public.audit_logs
for select to authenticated using (public.is_nodeguard_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'voice-contexts',
  'voice-contexts',
  false,
  10485760,
  array['audio/mpeg', 'audio/mp4', 'audio/aac', 'audio/wav', 'audio/ogg']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "authenticated users read voice context files" on storage.objects;
create policy "authenticated users read voice context files" on storage.objects
for select to authenticated
using (
  bucket_id = 'voice-contexts'
  and exists (
    select 1
    from public.voice_contexts vc
    where vc.storage_path = storage.objects.name
      and public.can_read_nodeguard_incident(vc.incident_id)
  )
);

create or replace function public.assign_nodeguard_responder(
  p_responder_code text,
  p_incident_public_id text,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_role public.user_role;
  v_incident public.incidents%rowtype;
  v_responder public.responders%rowtype;
begin
  v_actor := case when auth.role() = 'service_role' then p_actor_id else auth.uid() end;
  select role into v_role from public.profiles where id = v_actor and is_active;
  if v_actor is null or v_role is null or (
    v_role not in ('admin', 'super_admin')
    and exists (select 1 from public.responders where profile_id = v_actor)
  ) then
    raise exception 'Authorized dispatch-desk personnel access is required.';
  end if;

  select * into v_incident
  from public.incidents
  where public_id = p_incident_public_id
  for update;
  if not found then raise exception 'Incident not found: %', p_incident_public_id; end if;
  if v_incident.status in ('resolved', 'closed', 'false_alert') then
    raise exception 'Final incidents cannot be reassigned.';
  end if;

  select * into v_responder
  from public.responders
  where public_code = p_responder_code
  for update;
  if not found then raise exception 'Responder not found: %', p_responder_code; end if;
  if v_responder.availability = 'offline' then
    raise exception 'Offline responders cannot be assigned.';
  end if;

  update public.incidents
  set assigned_responder_name = v_responder.name,
      assigned_unit = v_responder.agency_unit,
      status = 'assigned'
  where id = v_incident.id;

  update public.responders
  set availability = 'dispatched',
      current_assignment = v_incident.public_id,
      last_status_update = now()
  where id = v_responder.id;

  insert into public.incident_assignments (
    incident_id, responder_id, assigned_unit, assigned_by, notes
  ) values (
    v_incident.id, v_responder.id, v_responder.agency_unit, v_actor,
    'Assigned from NodeGuard dashboard.'
  );

  insert into public.notifications (
    recipient_profile_id, responder_id, incident_id, type, title, message
  ) values (
    v_responder.profile_id, v_responder.id, v_incident.id, 'assignment',
    'New incident assigned: ' || v_incident.public_id,
    v_incident.public_id || ' assigned to ' || v_responder.name || '.'
  );

  insert into public.audit_logs (actor_profile_id, action, entity_type, entity_id, details)
  values (
    v_actor, 'assign_responder', 'incident', v_incident.public_id,
    jsonb_build_object('responder_code', v_responder.public_code, 'responder_name', v_responder.name)
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.assign_nodeguard_responder(text, text, uuid)
to authenticated, service_role;

create or replace function public.assign_nodeguard_resource(
  p_resource_code text,
  p_incident_public_id text,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_role public.user_role;
  v_incident public.incidents%rowtype;
  v_resource public.response_resources%rowtype;
begin
  v_actor := case when auth.role() = 'service_role' then p_actor_id else auth.uid() end;
  select role into v_role from public.profiles where id = v_actor and is_active;
  if v_actor is null or v_role is null or (
    v_role not in ('admin', 'super_admin')
    and exists (select 1 from public.responders where profile_id = v_actor)
  ) then
    raise exception 'Authorized dispatch-desk personnel access is required.';
  end if;

  select * into v_incident from public.incidents
  where public_id = p_incident_public_id for update;
  if not found then raise exception 'Incident not found: %', p_incident_public_id; end if;
  if v_incident.status in ('resolved', 'closed', 'false_alert') then
    raise exception 'Resources cannot be assigned to a final incident.';
  end if;

  select * into v_resource from public.response_resources
  where public_code = p_resource_code for update;
  if not found then raise exception 'Resource not found: %', p_resource_code; end if;
  if v_resource.status <> 'available' then
    raise exception 'Only available resources can be assigned.';
  end if;

  update public.response_resources
  set status = 'dispatched', assigned_incident_public_id = v_incident.public_id
  where id = v_resource.id;

  insert into public.resource_assignments (resource_id, incident_id, assigned_by, notes)
  values (v_resource.id, v_incident.id, v_actor, 'Assigned from NodeGuard dashboard.');

  insert into public.audit_logs (actor_profile_id, action, entity_type, entity_id, details)
  values (
    v_actor, 'assign_resource', 'incident', v_incident.public_id,
    jsonb_build_object('resource_code', v_resource.public_code, 'unit_name', v_resource.unit_name)
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.assign_nodeguard_resource(text, text, uuid)
to authenticated, service_role;

create or replace function public.validate_nodeguard_incident(
  p_incident_public_id text,
  p_validation_status text,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_role public.user_role;
begin
  if p_validation_status not in ('pending_review', 'confirmed', 'false_alarm') then
    raise exception 'Invalid validation status.';
  end if;

  v_actor := case when auth.role() = 'service_role' then p_actor_id else auth.uid() end;
  select role into v_role from public.profiles where id = v_actor and is_active;
  if v_actor is null or v_role is null or v_role not in ('personnel', 'admin', 'super_admin') then
    raise exception 'Authorized personnel access is required.';
  end if;

  update public.incidents
  set validation_status = p_validation_status,
      validated_by = case when p_validation_status = 'pending_review' then null else v_actor end,
      validated_at = case when p_validation_status = 'pending_review' then null else now() end,
      status = case when p_validation_status = 'false_alarm' then 'false_alert' else status end
  where public_id = p_incident_public_id;
  if not found then raise exception 'Incident not found: %', p_incident_public_id; end if;

  insert into public.audit_logs (actor_profile_id, action, entity_type, entity_id, details)
  values (
    v_actor, 'validate_incident', 'incident', p_incident_public_id,
    jsonb_build_object('validation_status', p_validation_status)
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.validate_nodeguard_incident(text, text, uuid)
to authenticated, service_role;

drop function if exists public.set_device_buzzer(text, boolean, text);
create function public.set_device_buzzer(
  p_device_id text,
  p_active boolean,
  p_source text default 'personnel_app',
  p_requested_by uuid default null
)
returns table (
  device_id text,
  buzzer_active boolean,
  buzzer_updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_allowed boolean;
begin
  if p_source not in ('dashboard', 'personnel_app', 'device') then
    raise exception 'Invalid buzzer command source: %', p_source;
  end if;

  v_actor := case when auth.role() = 'service_role' then p_requested_by else auth.uid() end;
  select (
    p_source = 'device'
    or exists (
      select 1 from public.profiles p
      where p.id = v_actor and p.is_active
        and (
          p.role in ('admin', 'super_admin')
          or not exists (select 1 from public.responders own where own.profile_id = p.id)
          or exists (
            select 1
            from public.responders r
            join public.incidents i on i.assigned_responder_name = r.name
            where r.profile_id = p.id
              and i.device_id = p_device_id
              and i.status not in ('resolved', 'closed', 'false_alert')
          )
        )
    )
  ) into v_allowed;
  if not coalesce(v_allowed, false) then
    raise exception 'You are not authorized to control this node buzzer.';
  end if;

  update public.device_locations dl
  set buzzer_active = p_active, buzzer_updated_at = now()
  where dl.device_id = p_device_id
  returning dl.device_id, dl.buzzer_active, dl.buzzer_updated_at
  into device_id, buzzer_active, buzzer_updated_at;
  if not found then raise exception 'Device not found: %', p_device_id; end if;

  insert into public.device_buzzer_commands (device_id, active, requested_by, source)
  values (p_device_id, p_active, v_actor, p_source);

  insert into public.audit_logs (actor_profile_id, action, entity_type, entity_id, details)
  values (
    v_actor, 'set_device_buzzer', 'device', p_device_id,
    jsonb_build_object('active', p_active, 'source', p_source)
  );

  return next;
end;
$$;

grant execute on function public.set_device_buzzer(text, boolean, text, uuid)
to authenticated, service_role;

insert into public.response_resources (
  public_code, resource_type, unit_name, agency, status, base_location,
  assigned_incident_public_id, notes
) values
('AMB-001', 'Ambulance', 'Ambulance 01', 'MDRRMO', 'available', 'MDRRMO Office', null, 'Basic life support unit'),
('AMB-002', 'Ambulance', 'Ambulance 02', 'EMS', 'available', 'Km. 5 Pico', null, 'Medical transport unit'),
('FIRE-001', 'Fire Truck', 'Fire Truck 01', 'BFP', 'available', 'BFP La Trinidad Station', null, 'Fire suppression unit'),
('FIRE-002', 'Fire Truck', 'Fire Truck 02', 'BFP', 'under_maintenance', 'BFP La Trinidad Station', null, 'Not available for dispatch'),
('RESCUE-001', 'Rescue Vehicle', 'Rescue Vehicle 01', 'MDRRMO', 'available', 'MDRRMO Office', null, 'Equipped with rescue tools'),
('PATROL-001', 'Patrol Vehicle', 'PNP Patrol 01', 'PNP', 'available', 'Police Station', null, 'Security/public safety response'),
('RADIO-001', 'Communication Radio', 'Portable Radio Set A', 'MDRRMO', 'available', 'Operations Desk', null, 'Four handheld radios'),
('KIT-001', 'First Aid Kit', 'First Aid Kit 01', 'EMS', 'reserved', 'School Area', null, 'Reserved for school event standby'),
('EQUIP-001', 'Rescue Equipment', 'Extrication Tool Kit', 'MDRRMO', 'available', 'MDRRMO Office', null, 'Cutting and lifting tools'),
('WATER-001', 'Water Rescue Equipment', 'Water Rescue Kit', 'MDRRMO', 'unavailable', 'MDRRMO Storage', null, 'Awaiting inspection')
on conflict (public_code) do nothing;

do $$
begin
  alter publication supabase_realtime add table public.response_resources;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.resource_assignments;
exception when duplicate_object then null;
end $$;
